apiVersion: v1
kind: ConfigMap
metadata:
  namespace: $name;format="normalize"$
  name: $name;format="normalize"$-{{{ branch }}}-config-map
data:
{{ #configMap }}
  {{{ key }}}: {{{ value }}}
{{ /configMap }}
