apiVersion: v1
kind: Service
metadata:
  namespace: $name;format="normalize"$
  name: $name;format="normalize"$-{{{ branch }}}-service
spec:
  selector:
    app: $name;format="normalize"$-{{{ branch }}}
  ports:
    - port: 9000
