---
- import_playbook: values.yml
- import_playbook: aws-resources.yml
- hosts: localhost
  connection: local
  vars:
    docker_image: "{{ ecr_url }}:{{ git_commit }}"
    kops_state_store: "s3://kops.ruchij.com"
    secrets:
      SAMPLE_SECRET: "secret-value"
    config_values:
      SAMPLE_KEY: "sample-value"
  tasks:
    - name: Create output directory
      file:
        path: output
        state: directory

    - name: Render K8s resource files
      template:
        src: "{{ item }}"
        dest: "output/{{ item | basename }}"
      with_fileglob:
        - ../k8s/*.yml

    - name: Fetch kubectl configuration
      shell: KOPS_STATE_STORE="{{ kops_state_store }}" kops export kubecfg k8s.ruchij.com

    - name: Create Namespace
      command: kubectl apply -f output/namespace.yml

    - name: Create ConfigMap
      command: kubectl apply -f output/config-map.yml

    - name: Create Secrets
      command: kubectl apply -f output/secrets.yml

    - name: Deploy to K8s cluster
      command: kubectl apply -f output/

    - name: Wait for successful deployment
      command: kubectl rollout status deployment/$name;format="normalize"$-{{ git_branch }}-deployment -n $name;format="normalize"$
