FROM openjdk:8-jdk

RUN apt-get update && \
    apt-get install apt-transport-https bc ca-certificates software-properties-common -y

WORKDIR /opt

COPY . .

EXPOSE 9000

ENTRYPOINT ["bash"]

CMD ["/opt/bin/$name;format="normalize"$"]
