FROM ubuntu as builder

WORKDIR /opt

RUN apt update && \
    apt install unzip -y

COPY target/universal .

RUN unzip $name;format="normalize"$-*.zip -d build && \
    mv build/$name;format="normalize"$-* $name;format="normalize"$

FROM openjdk:8-jdk-slim

ARG git_branch="unspecified"
ARG git_commit="unspecified"
ARG build_timestamp="1970-01-01T00:00:00Z"

ENV GIT_BRANCH \$git_branch
ENV GIT_COMMIT \$git_commit
ENV DOCKER_BUILD_TIMESTAMP \$build_timestamp

WORKDIR /opt/$name;format="normalize"$

COPY --from=builder /opt/$name;format="normalize"$ .

EXPOSE 9000

ENTRYPOINT ["bash"]

CMD ["/opt/$name;format="normalize"$/bin/$name;format="normalize"$"]
