apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  namespace: $name;format="normalize"$
  name: $name;format="normalize"$-{{ git_branch }}-certificate
spec:
  secretName: {{ git_branch }}-$name;format="normalize"$-tls
  issuerRef:
    name: lets-encrypt
    kind: ClusterIssuer
  dnsNames:
    - {{ git_branch }}.$name;format="normalize"$.ruchij.com
  acme:
    config:
      - dns01:
          provider: route53-dns
        domains:
          - {{ git_branch }}.$name;format="normalize"$.ruchij.com
