apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: $name;format="normalize"$
  name: $name;format="normalize"$-{{ git_branch }}-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - secretName: {{ git_branch }}-$name;format="normalize"$-tls
      hosts:
        - {{ git_branch }}.$name;format="normalize"$.ruchij.com
  rules:
    - host: {{ git_branch }}.$name;format="normalize"$.ruchij.com
      http:
        paths:
          - backend:
              serviceName: $name;format="normalize"$-{{ git_branch }}-service
              servicePort: 9000
